version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "1033:1033"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    ports:
      - "9002:9002"
